server:
  port: 8090
spring:

  datasource:
    username: 'postgres'
    password: '1234'
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/product'

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
